CMakeLists.txt
README.md
cmake/common.cmake
include/tiovx_color_convert_module.h
include/tiovx_dl_color_blend_module.h
include/tiovx_dl_pre_proc_module.h
include/tiovx_img_mosaic_module.h
include/tiovx_modules_common.h
include/tiovx_multi_scaler_module.h
src/CMakeLists.txt
src/tiovx_color_convert_module.c
src/tiovx_dl_color_blend_module.c
src/tiovx_dl_pre_proc_module.c
src/tiovx_img_mosaic_module.c
src/tiovx_multi_scaler_module.c
test/CMakeLists.txt
test/app_common.c
test/app_common.h
test/app_tiovx_color_convert_module_test.c
test/app_tiovx_dl_pre_proc_module_test.c
test/app_tiovx_img_mosaic_module_test.c
test/app_tiovx_multi_scaler_module_test.c
test/main.c

- used cmake to build
- comprises of 5 modules library
- currently has only 4 test cases
- more cleanup required
- validated on PSDK 8.0 RC9

module: first draft of modules with cmake

---

README.md

readme: fixed formatting issue

---

cmake/common.cmake
include/tiovx_modules_common.h
test/app_common.h

cmake: added path to tiovx_dev to work with internal builds

---

CMakeLists.txt
include/tiovx_dl_draw_box_module.h
src/CMakeLists.txt
src/tiovx_dl_draw_box_module.c
test/CMakeLists.txt
test/app_tiovx_dl_draw_box_module_test.c

modules: added dl draw box module

---

test/app_common.c
test/app_tiovx_dl_pre_proc_module_test.c

- Tested different combination of NCHW, NHWC
- Tested different bit-depths

dl-pre-proc: Validated tests with RGB input

---

test/app_common.c
test/app_common.h
test/app_tiovx_dl_color_blend_module_test.c

modules: updated dl-color-blend test

---

include/tiovx_aewb_module.h
test/app_common.c
test/app_common.h
test/app_tiovx_aewb_module_test.c

- moved the user_data_object allocate/assign/delete/release functions to app_common.c

module: clean up of AEWB module

---

include/tiovx_aewb_module.h
src/tiovx_aewb_module.c
test/app_tiovx_aewb_module_test.c

modules: AEWB object to have Sensor object pointer

---

include/tiovx_ldc_module.h
src/CMakeLists.txt
src/tiovx_ldc_module.c
test/CMakeLists.txt
test/app_tiovx_ldc_module_test.c

module: first draft of ldc module

---

src/tiovx_aewb_module.c
src/tiovx_color_convert_module.c
src/tiovx_dl_color_blend_module.c
src/tiovx_dl_pre_proc_module.c
src/tiovx_img_mosaic_module.c
src/tiovx_ldc_module.c
src/tiovx_multi_scaler_module.c

module: fixed the background image as NULL issue

---

src/CMakeLists.txt
test/CMakeLists.txt

makefile: removed aewb related files to build

---

src/tiovx_sensor_module.c

modules: updated sensor list to IMX219

---

cmake/common.cmake
test/main.c

cmake: updated SOC version and fixed header path

---

cmake/common.cmake
test/main.c

makefile: corrected 8.1 sdk paths

---

cmake/common.cmake

cmake: corrected path to platform folders

---

cmake/common.cmake

cmake: updated to 8.1 paths

---

test/app_tiovx_viss_module_test.c

viss-test: updated test to get AE dynamic params

---

test/app_tiovx_viss_module_test.c

test: viss: Fix OUTPUT DIMS for AM62 case

---

cmake/common.cmake

build: Add support to install the test bin

---

test/app_tiovx_viss_module_test.c

test: viss: Change graph param based on ir or bayer

---

test/app_tiovx_multi_scaler_module_test.c

Signed-off-by: ravi-rahul <r-ravikumar@ti.com>

test: Fix MSC test

---

cmake/common.cmake

[cmake] Add support to install output directory

---

test/app_common.c
test/app_common.h
test/app_tiovx_viss_module_test.c

[AM62A] Updated testcase

---

cmake/common.cmake

Signed-off-by: Aniket Limaye <a-limaye@ti.com>

SOC: Build for J721S2 instead of J721E

---

cmake/common.cmake
cmake/cross_compile_aarch64.cmake
include/tiovx_modules_common.h
test/app_common.h

align with PSDK RTOS 8.4

---

src/tiovx_viss_module.c

Signed-off-by: Shubham Jain <a0492788@ti.com>

[AM62A] modify h3a input to PCID

---

cmake/common.cmake

cmake: Add support to install the test bin

---

src/tiovx_sensor_module.c

sensor: Fixed sensor names as strings

---

include/tiovx_ldc_module.h
src/tiovx_ldc_module.c
test/app_tiovx_ldc_module_test.c

Add support to configure start x&y coordinates
for LDC output croping

test/modules: ldc: Configure init coordinates

---

include/tiovx_sensor_module.h
src/tiovx_sensor_module.c

Add list of sensor supported in the header file
doxygen comments

modules: sensor: Add list of sensors supported

---

include/tiovx_modules_common.h

Required for pyramid when levels are 5 or more

common: Increase the MAX ref handel count

---

cmake/common.cmake

Perception include folder name is changed in SDK.
Align with the same

meson: Align with updates in SDK
